[theme]
primaryColor = "#10b981"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1a3a3a"
textColor = "#e0f2fe"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "error"
